// app/javascript/components/meeting/attendee/Attendees.jsx
import React from 'react';

import Autocomplete from '../../common/Autocomplete';

import Utils from 'utils';

export default class Attendees extends React.Component {

  componentDidUpdate(prevProps, prevState) {
    if (this.props.attendees.length > prevProps.attendees.length) {
      this.autocomplete.focus();
    }
  }

  autocompletePath = (autocompleteValue) => {
    return '/attendees/autocomplete?email=' + encodeURIComponent(autocompleteValue);
  }

  parseAutocompleteResponse = (data) => {
    var attendeeIDs = this.props.attendees.map(it => it.id);
    return data.filter(it => attendeeIDs.indexOf(it.id) === -1);
  }

  onAutocompleteItemSelected = (item) => {
    this.props.onAttendeeSelect(item.email, this.props.meetingID);
  }

  onAutocompleteEmptySubmit = (autocompleteText) => {
    this.props.onAttendeeSelect(autocompleteText, this.props.meetingID);
  }

  noAttendeesFoundMessage = (autocompleteText) => {
    return `No attendees found. Hit 'Enter' or click here to add '${autocompleteText}.'`
  }

  render() {
    return (
      <div>
        <Autocomplete
          id="attendees-autocomplete"
          className="autocomplete bg-white flex-no-shrink"
          placeholder="Add Attendee"
          method="GET"
          url={this.autocompletePath}
          parseResponse={this.parseAutocompleteResponse}
          renderItem={(item) => item.email}
          onItemSelected={this.onAutocompleteItemSelected}
          onEmptySubmit={this.onAutocompleteEmptySubmit}
          noResultsMessage={this.noAttendeesFoundMessage} />

        <ul className="list mt-4 attendees-list" style={{ borderWidth: 0 }}>
          {this.props.attendees.map((attendee, index) => {
            return (
              <li className={`list-item ${index == 0 ? "border" : "border-r border-l border-b"}`} key={attendee.id}>
                <div className="media">
                  <img src={Utils.getGravatarUrl(attendee.email)} className="avatar" />
                  <div className="media-text">
                    <span className="truncate">
                      {attendee.email.slice(0, 25)}
                      {attendee.email.length > 25 && "..."}
                    </span>
                  </div>
                </div>
                <button className="list-floating-content"
                    onClick={() => this.props.onAttendeeRemove(attendee.email, this.props.meetingID)}>
                  <i className="fa fa-trash"></i>
                </button>
              </li>
            );
          })}
        </ul>
      </div>
    );
  }
};

// app/javascript/src/views/meeting/sidebar/Attendees.vue
<template>
  <div>
    <autocomplete
      id="attendees-autocomplete"
      class="autocomplete bg-white flex-no-shrink"
      placeholder="Add Attendee"
      method="GET"
      :url="value => `/attendees/autocomplete?email=${encodeURIComponent(value)}`"
      :parseResponse="parseAutocompleteResults"
      :renderResultItem="item => item.email || item"
      @select-result="addAttendee"
      :renderNoResultsMessage="renderNoResultsMessage" />

    <ul class="list mt-4 attendees-list" :style="{ borderWidth: 0 }">
      <li v-for="(attendee, index) in meeting.attendees"
          :key="attendee.id"
          :class="['list-item', index == 0 ? 'border' : 'border-r border-l border-b']">
        <div class="media">
          <img :src="attendeeAvatarUrl(attendee)" class="avatar" />
          <div class="media-text">
            <span class="truncate">
              {{ attendee.email.slice(0, 25) }}<span v-if="attendee.email.length > 25">...</span>
            </span>
          </div>
        </div>
        <button class="list-floating-content" @click="removeAttendee(attendee)">
          <i class="fa fa-trash"></i>
        </button>
      </li>
    </ul>
  </div>
</template>

<script>
import Utils from '../../../../utils'
import Autocomplete from '../../../components/Autocomplete'

export default {
  components: {
    Autocomplete,
  },

  data() {
    return {
      meeting: this.$store.state.meeting
    }
  },

  methods: {
    attendeeAvatarUrl(attendee) {
      return Utils.getGravatarUrl(attendee.email)
    },

    addAttendee(attendeeOrEmail) {
      this.$store.dispatch('addAttendee', attendeeOrEmail.email || attendeeOrEmail)
    },

    removeAttendee(attendee) {
      this.$store.dispatch('removeAttendee', attendee.email)
    },

    parseAutocompleteResults(autocompleteResults) {
      const attendeeIDs = this.meeting.attendees.map(attendee => attendee.id)
      return autocompleteResults.filter(result => attendeeIDs.indexOf(result.id) === -1)
    },

    renderNoResultsMessage(autocompleteText) {
      return `No attendees found. Click here to add '${autocompleteText}'`
    },
  }
}
</script>

<style lang="scss" scoped>

</style>
